window.svg = {
    'arrowSvg' : [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="73px" height="103px" viewBox="-0.5 -0.5 73 103" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-15T13:04:30.346Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; version=&quot;20.7.2&quot; etag=&quot;a6G8JE2q17uD9P-y-rbX&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;jZPbbsIwDIafppdDbQODXUIH2zRNmoS2XUdNaCLSukpTaHn6JdTpQQgJcVHn8yGO/ROQJG/eNC3FFzCugjhkTUBegziOwkVoP460HVm8RB3ItGQYNIC9vHCfibSWjFeTQAOgjCynMIWi4KmZMKo1nKdhB1DTW0ua8RuwT6m6pX+SGdHRlX+W4+9cZsLfHIXoyakPRlAJyuA8QmQbkEQDmM7Km4QrNzw/ly5vd8fbN6Z5YR5J+DCfp/qnhd/v4/qi6gJSIZ6wyomqGh+MzZrWT0CYXFkrCsimf0JoD4xWgjM8UCWzwtqpbYZrC05cG2nHuEZHLhlzFV2N0lXOm8wpZtYtKe6+rqwTSjh7dqZT0fx6l9R2uRJcpQK0m+ymAJMKvL4yGo48AQX62jQJ4/VyRXqPX50jB6nUKDLauZ/lOAnbN2/ujjjqF2cVzyHnRrc2BBPmfvko9l7F50E6S0RirBqfR1GtWV96WKg1cKf+OGjn6hv9A8n2Hw==&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <path d="M -14 37 L 46 37 L 46 16 L 86 51 L 46 86 L 46 65 L -14 65 L -14 51 Z" fill="#1f1f1f" stroke="#02a783" stroke-width="3" stroke-miterlimit="10" transform="rotate(270,36,51)" pointer-events="all" />
      </g>
    </svg>`],

    'pumpSvg' : [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="93px" height="93px" viewBox="-0.5 -0.5 93 93" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-15T13:07:09.212Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; version=&quot;20.7.2&quot; etag=&quot;gBhI4TNN7PyYEfkiHVuG&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;rZRda4MwFIZ/jZcDNbjay9a12xiDQdl2HUxqQmOOxFi1v35JjV90ZSsUL8x5zkeS9xz1UJI3zwoX7B0IFV7ok8ZDT14YBn7km5clbUeiZdCBTHHigkaw4yfaZzpacULLWaAGEJoXc5iClDTVM4aVgnoetgcx37XAGb0AuxSLS/rNiWYdjftrWf5Cecb6nQPfeXLcBztQMkygniC08VCiAHS3ypuECiter0uXt73iHQ6mqNT/SXjVb8fqs4Wvj8PqJCoJKWMPYVfliEXlLuwOq9teAa04lpm11jXjmu4KnFpXbRpuGNO5MFZglqVWcKAJCFDnVOSHq0WMBk8voCV7LsQkMtjax3DClWkjB2m4BGXj1+6MVGnaXL18MEhqZpFCTrVqTYhLQAvXBTeGYezsemzq0iE26eejY9iNUTZUHpU2Cyf2DcKjv4U3VcyU/0N3XBbd6O95Q8mdGnEX0aO56NGl6PEvose3i27M8Us6+yb/I7T5AQ==&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <path d="M 16 16 L 76 61 L 16 106 Z" fill="#1f1f1f" stroke="#02a783" stroke-width="3" stroke-miterlimit="10" transform="rotate(270,46,61)" pointer-events="all" />
        <ellipse cx="46" cy="41" rx="40" ry="40" fill="#1f1f1f" stroke="#02a783" stroke-width="3" pointer-events="all" />
      </g>
    </svg>`],

    'smallTowerSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="73px" height="453px" viewBox="-0.5 -0.5 73 453" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-15T13:18:02.902Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; version=&quot;20.7.2&quot; etag=&quot;rY4YoY4zrNDsCerucy50&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;jZNdb4IwFIZ/DZdLgGrUS2W6LcuSJWbbdUOPtLFwSCkC/vq10vIRY2K4oH3Oe/rxntOAJHn7pmjJv5CBDOKQtQF5DeI4Cpeh+VnS9WS5iXqQKcGcaARHcQWf6WgtGFQzoUaUWpRzmGJRQKpnjCqFzVx2QjnftaQZ3IFjSuU9/RNM856u/bUsfweRcb9zFLpITr3YgYpThs0EkX1AEoWo+1HeJiCted6XPu/wIDocTEGhn0n40J+X+qfD3+/z9irrAlPOX1b9Khcqa3dhd1jdeQcU1gUDu0gUkF3DhYZjSVMbbUzNDeM6ly5caYVnSFCiumWTMN6u1mSIeA8tOQkpJ8roYD/DmVCmkgILwyusrX5HVep6g6zN1J0alIb2oR3RYLLpTsActOqMxCUsfIe5xty4aTNWeeUQnxR44StPXWNlw8qj92bg7PfTscy32OSxkP0/&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <rect x="-189" y="191" width="450" height="70" rx="26.6" ry="26.6" fill="#1f1f1f" stroke="#02a783" stroke-width="3" transform="rotate(90,36,226)" pointer-events="all" />
      </g>
    </svg>`],

    'airCooledCondenserSvg' : [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="183px" height="63px" viewBox="-0.5 -0.5 183 63" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-15T13:24:30.843Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; version=&quot;20.7.2&quot; etag=&quot;LzM57sqTgjJC536vL9oB&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;3ZRbT4MwFIB/DY8mlG7KHiduaoyJyaI+N3BGmxUO6cqA/XrLaLlEF/VBEw0PtN85p5evBY9GWX2rWMEfMQHpBX5Se/TGCwLiz33zaknTkfmCdCBVIrFJA9iII7hKS0uRwH6SqBGlFsUUxpjnEOsJY0phNU3bopzOWrAU3oFNzOR7+ioSzTsaum21/A5Eyt3MxLeRjLlkC/acJViNEF15NFKIumtldQSylee8dHXrM9F+YQpy/ZWCe/1wKJ8bfHnaLY+yzDHm/CLsRjkwWdoN28XqxhlQWOYJtIP4Hr2uuNCwKVjcRitz5oZxnUnTI6a51wp3EKFEdaqmfrC8CmkfcQ5bshVSjjLJun0Mt0sCpaE+u1fSGzRXDzADrRqTYgvozEq3t44sbL8azpCElvHR+V1axuy1SfuhB7OmYeV+Q/Tic9FmFHOr4e9Ink8l99/sSPJHjoOfcuzm/0+SZ/TXJJvu8Dc6xUb/dLp6Aw==&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <rect x="1" y="1" width="180" height="60" fill="#1f1f1f" stroke="#02a783" stroke-width="3" pointer-events="all" />
        <ellipse cx="51" cy="31" rx="40" ry="10" fill="#1f1f1f" stroke="#02a783" stroke-width="3" pointer-events="all" />
        <ellipse cx="131" cy="31" rx="40" ry="10" fill="#1f1f1f" stroke="#02a783" stroke-width="3" pointer-events="all" />
      </g>
    </svg>`],

    'bigTowerSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="91px" height="456px" viewBox="-0.5 -0.5 91 456" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-16T06:07:05.002Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; etag=&quot;TgXUNxJIk72MW23fWz2U&quot; version=&quot;20.7.2&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;1ZZZb+MgFIV/jR9bYeOtj0nazmikSJGi2R6RfWvTYmNhsvXXDxTwEjdKp9MqGuUh5gOu4ZxjbA8vqv0XQZpyyXNgXoDyvYdvvSDwUYTUnyYHS+Ib35BC0Nww1IM1fQY31dINzaG1zCDJOZO0GcOM1zVkcsSIEHw3HvbAWT4CDSlgAtYZYVP6k+ayNDR1+9L8K9CidHf2ke2piBtsQVuSnO8GCN95eCE4l+aq2i+AafXGutyf6O0WJqCWb5nw4/Eb0OWyeK623+ePMFtWzeoqwqbMlrCN3bFdrTw4CQTf1DnoKr6H57uSSlg3JNO9O+W6YqWsmO1upeBPsOCMi5fZGAWzJMVdjxNRkwfK2GCkf69/iudUKCsprxVv+UaPnxOR2XCESrl5A4JWIEHoldC6UBwpbDcDQsL+pEx+J76KLXBVRhzUEDsBx7GZYhN7FSWhAbuB/6lB5cB6HLnY2cgVXe3eFXVhjfkbk8LzJklBSV3o1qUc+hDtk+torH7gVB2qH03Vj6PPEj/6754Q/+aD7EjxxI4gndjhzpChHT5KPsuP+LwfUOczffarVs1rGOvfm6VPjPYJZFa6xrE1neBja0JFso3YdpYrQcXhl65yjdTOLfhtAMYO3O7tjUzrMGyt3Ik2Osogn7yejtxT70MiCpBnz4+pzUMP0dRDxwQwIul2vI7XfLV3WHGqVtinKEEnHmlXQyVYZGCnDd9gR5VCjE4eD66WEWNS6yVq3db/IX3J5dOXHKfvrVG5WALSaHqOxO/NQHi21rszoJr995gZ3n/W4rs/&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <rect x="-130.5" y="132.5" width="351" height="88" rx="36.96" ry="36.96" fill="#1f1f1f" stroke="#02a783" stroke-width="3" transform="rotate(90,45,176.5)" pointer-events="all" />
        <path d="M 12.5 314 L 77.5 356.5 L 12.5 399 Z" fill="#1f1f1f" stroke="#02a783" stroke-width="3" stroke-miterlimit="10" transform="rotate(90,45,356.5)" pointer-events="all" />
        <rect x="-8.5" y="374" width="107" height="53" rx="10.07" ry="10.07" fill="#1f1f1f" stroke="#02a783" stroke-width="3" transform="rotate(90,45,400.5)" pointer-events="all" />
        <path d="M 5 324 Q 5 324 84.69 324.45" fill="none" stroke="#1f1f1f" stroke-width="4" stroke-miterlimit="10" pointer-events="stroke" />
        <path d="M 20.5 349 Q 20.5 349 69.5 349" fill="none" stroke="#1f1f1f" stroke-width="7" stroke-miterlimit="10" pointer-events="stroke" />
      </g>
    </svg>`],

    'refluxDrumSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="220px" height="173px" viewBox="-0.5 -0.5 220 173" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-15T16:37:59.773Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; etag=&quot;52zN4q9x_zDYqyMxSRby&quot; version=&quot;20.7.2&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;zVjbbqMwEP0aHlsBtmN4bNJ2VytFqlTt7dECF9wCRo5z69evXRsIkIRQ2t1VH4qPfcbDmcEzjgMW+e6LIGW65DHNHN+Ndw64dXzfc5Gr/mlkb5FZ6BkkESw2mNsAj+yVVlSLrllMVxYzkOQ8k6xsgxEvChrJFkaE4Nv2sieexS2gJAntAY8RyfroTxbL1KBB9V4a/0pZklY7e66dyUm12AKrlMR8ewCBOwcsBOfSPOW7Bc20em1d7k/M1o4JWshLCD+ev1G2XCav+eb7/JneLPPy4coLjJkNydb2ja23cl9JIPi6iKm24jlgvk2ZpI8lifTsVkVdYanMMzu9koK/0AXPuHhjA9e/wQGoZyoRNfLEsuxgpXev/xQeM6FCyXih8BVf6/VzIiKbHEp6MLdeUyHp7qQeXq2yyk/KcyrFXi2xBIgtxabmFZhhA2ybQCMLpa0YA5tfNreS2nYjv3qwERgTjfA/jMbHKw9msK089GFPed87In2IP0l5/wLlaRHf6BNFjQpe0LbSTVi0SKsXKqO0GowIAo3V6WO35EKmPOEFye4adB6txaYOv/FRk8aG4jDH3b7QFSZoRiTbtM0fU9/u8MCZ2riJNEadbwzO2jbU9y0iammHp1fHEsLoumsLdbJBEpFQ2bOlgkb2B8tKvWA1ymn/rG8g6J4kowkzcJ6Aw6kE7J4nhLOpBBieJUCvp9JYwoBLEPhTCeh84CACUwlDLmE4lTAka4CnEgZcQt7IOPQJA7Iiv5saowkYnyeAYCoBDRBQ7x3GEoZcwr3kG0sYOGYQ7h4CbYJ6MKdvU5nrGvT+Yl19tX+lWNd9ULtYw24pVgVX7H9pK9eqftjx78PJ253dw4z21WjHpOEhO6pZ6rkh6UHFcS6s+0qSt/p6Qc9piufgwn/WSYSdguajoG3j0k4Cwm5pdDuWTvQRH5a+YDh91WWxND3gpzb59cpjVy7nE+5Yftjv9BHqZw10TyfIiUZfDZvLtIlV85sEuPsD&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <rect x="80" y="86" width="113" height="57" rx="28.5" ry="28.5" fill="#1f1f1f" stroke="#02a783" stroke-width="3" transform="rotate(90,136.5,114.5)" pointer-events="all" />
        <rect x="1" y="1" width="217" height="97" rx="48.5" ry="48.5" fill="#1f1f1f" stroke="#02a783" stroke-width="3" pointer-events="all" />
        <path d="M 12 79 Q 12 83 15 83 Q 18 83 18 72.5 Q 18 62 17 62 Q 16 62 16 58.5 Q 16 55 24.5 55 Q 33 55 33 65.5 Q 33 76 40.5 76 Q 48 76 48 65.5 Q 48 55 58.5 55 Q 69 55 69 64 Q 69 73 79.5 73 Q 90 73 90 64 Q 90 55 100.5 55 Q 111 55 111 65.5 Q 111 76 117.5 76 Q 124 76 124 65.5 Q 124 55 136.5 55 Q 149 55 149 64 Q 149 73 153.5 73 Q 158 73 158 60.5 Q 158 48 166.5 48 Q 175 48 175 58 Q 175 68 181.5 68 Q 188 68 188 58 Q 188 48 199 48 Q 210 48 210 55 Q 210 62 211.25 62 Q 212.5 62 212.5 68" fill="none" stroke="#02a783" stroke-width="3" stroke-miterlimit="10" pointer-events="stroke" />
        <path d="M 109.5 98 Q 109.5 98 163.75 98" fill="none" stroke="#1f1f1f" stroke-width="4" stroke-miterlimit="10" pointer-events="stroke" />
        <path d="M 115.5 123.5 Q 155.5 123.5 155.5 151 Q 155.5 178.5 115.5 178.5 Z" fill="#02a783" stroke="#02a783" stroke-width="3" stroke-miterlimit="10" transform="rotate(90,135.5,151)" pointer-events="all" />
      </g>
    </svg>`],

    
    'firedHeaterSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="149px" height="217px" viewBox="-0.5 -0.5 149 217" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-15T17:34:06.376Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; etag=&quot;MO65tE5wmXWKgSr8L-Za&quot; version=&quot;20.7.2&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;pVbbbuIwEP0aHlvFOAR4BEp3tRISEtrbo5VME7dOHDnmkn79jrFNEi7ZIoQEMycz4/GZY4cBXeSHb4qV2UomIAbDIDkM6MtgOCTBKMAfg9QOiabEIqniicWCBtjwT/CpDt3yBCqHWUhLKTQvu2AsiwJi3cGYUnLfDXuTIukAJUvhAtjETFyiv3miM4tO/L4M/h14mvmVSeCe5MwHO6DKWCL3LYguB3ShpNTWyg8LEIa9Li+vN56eGlNQ6K8k/Hr/AXy1Sj/z3c/5O8xWebl+oqEts2Ni63bsutW1pwAbL42pAb/n+4xr2JQsNtAep45YpnOBHkGz0kp+wEIKqY7ZNBjOxhN6euJJNMgbF6IVSV7NB/GEKxwll4VZASptIKOoKDCWURKhUzRd66A0HG6SQk5Uo0hB5qBVjSEuIQwnNsXp82nkJ7tvpk3CyGJZa9KIOpU5haWn4s0Q0HBzuGMmvqW+mUCRzIy60StkAd0ZKLktEjBLGMKqD9Bx5p07xhNv1e5YxdSEBI+FW18qnclUFkwsG3QOB67/mGWep1Hk/L9HnwTU+S8H18fRqVvOGhRH+kB5rEAqbbkAmXaArRdR4oGm4NGr2955SUui2Ui/WJBouVUxfOHYaKZS0P8NvJRfS11ecG1xeUyBYJrvug1fE5xbYS05bqVR93j6jNx3BE69vHwZu1mX2b4/zoqNInJRLIxot5gl5KIYapXVrbDSBFQ9jZ8fSzqa9DZ3JWHcv5tJ8GjCdNjfUvRoQkhG97V0fwLeo70tOVIeSIhIf0uOlFsJaFjxNPfp6Rhdu2LRbV6pNrz5Z0KX/wA=&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <path d="M 1 1 L 147 1 L 147 140 L 104 140 L 104 215 L 44 215 L 44 140 L 1 140 Z" fill="#1f1f1f" stroke="#02a783" stroke-width="3" stroke-miterlimit="10" transform="rotate(180,74,108)" pointer-events="all" />
        <path d="M 5.96 192.96 Q 1 193 1 193.5 Q 1 194 67 194 Q 133 194 133 176.5 Q 133 159 73 159 Q 13 159 13 147.5 Q 13 136 73 136 Q 133 136 133 124 Q 133 112 71.5 112 Q 10 112 10 101 Q 10 90 77.5 90 Q 145 90 144.96 79.97" fill="none" stroke="#02a783" stroke-width="3" stroke-miterlimit="10" pointer-events="stroke" />
      </g>
    </svg>`],

    'circleSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="83px" height="83px" viewBox="-0.5 -0.5 83 83" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-15T17:44:08.229Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; etag=&quot;BVZz3QuWVmLRsa52w_xa&quot; version=&quot;20.7.2&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;jZPfb4IwEMf/Gh5NgOqmj8J0yxKSJWbbc0NPqCuUlCroX7+rbRFiTAwPXD/3o9fvtQFJq/5d0abMJAMRxCHrA/IWxHEULkL8GXJ25GUVWVIoziwLb2DHL+BTHT1yBq1jFmkphebNFOayriHXE0aVkt00bC8Fm4CGFnAHdjkV9/SXM11auvTnMvwDeFH6naPQeSrqgx1oS8pkN0JkE5BUSamtVfUpCKPeVJftA+/QmIJaP5Pwc/gEnmXFpTp9JwdYZ1XzNZuvbJkTFUd3YtetPnsJsAyqjYukK7mGXUNz4+lw4shKXQlcRWjStrEj2PMecNek1Ur+QSqFVNdSJIzXr0syeLyihuy5EKPIaGs+5IwrLMplbbaEFssnrmVQGvqHYkSDxHg5QVag1RlDXAJZLGyKu5ezeeRAN5qym1w5GrBn1N2rYih9kx4Np75f3qZ89Y0eC9n8Aw==&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <ellipse cx="41" cy="41" rx="40" ry="40" fill="#1f1f1f" stroke="#02a783" stroke-width="3" transform="rotate(180,41,41)" pointer-events="all" />
      </g>
    </svg>`],   

    'cardSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="434px" height="434px" viewBox="-0.5 -0.5 434 434" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-16T08:19:31.879Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; etag=&quot;5ewQ6KsBSqot1SMpFJT0&quot; version=&quot;20.7.2&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;jZNNb8MgDIZ/TY6VQljX9rimH9GknXqY1MuEghvQSJ0SuqT79SMF8qGq0pRD8GMb8GsT0bRs95pV4gM5qCiJeRvRTZQkJJ7H9teRmyevK+JIoSV3LB7AQf5CSPX0KjnUnjlkEJWR1RTmeD5DbiaMaY3NNOyEik9AxQp4AIecqUf6KbkRji5DXR3PQBYinExi7ylZCPagFoxjM0J0G9FUIxq3KtsUVKfeVJfdE29/MQ1n858ElmX79LjI3i+LS75Rtfw61rPE7fLD1NUX7C9rbkGBRkgDh4rlnd3YNkd0LUyprEXsktWV0/0kW7BHrWuj8bsX68WSk1QqRYX6viElu+7rI0eeOHlbLKn1+FuBNtA+LZf0ItrxAyzB6JsNCQmrpUvxkzebk5UDzdDHF+qbI0Y97CHzs1P0mw/y2oVXOJhDJ+++0YOg2z8=&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <rect x="2" y="2" width="430" height="430" fill="#1f1f1f" stroke="#02a783" stroke-width="4" pointer-events="all" />
      </g>
    </svg>`],

    'mixingValveSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="75px" height="39px" viewBox="-0.5 -0.5 75 39" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-16T09:59:24.893Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; etag=&quot;XJnSbbNb2EB4hDx5pAmv&quot; version=&quot;20.7.2&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;7ZRNa8MwDIZ/TY6FJG6b9rilH2GwUw+DXoaJ1cTMiVPHXdL9+jm18kUpdDDKDiOH2I8kW3ol7JAwq7eKFumrZCAc32W1Q1aO73vuzDW/hpyRzJeeJYnizDK3Bzv+BW0o0hNnUCKzSEspNC/GMJZ5DrEeMaqUrMZuBynYCBQ0gSuwi6m4pm+c6dTSRVtXwyPgSdre7LloyWjrjKBMKZPVAJG1Q0IlpbarrA5BNOqNddncsHaJKcj1PQE0irbhPohejsExXomSv+/LydSe8knFCQvGZPW5VUArTvOk2T1XKdewK2jcmCrTccNSnQmz88yy1Ep+QCiFVJdQ4vpPwYJ0llbAqSEHLsTA09s0n+GYDygN9c1CvU4+M3ggM9DqbFwwgCyxKpy5CfGJBVXfQYKFpoPmkRnODc5M0h3dy2oWqOwPVJ7/q/wAlYO/pjLjyjxJXObNDVDq3xF+SsjDhDfb/oG62AbvPFl/Aw==&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <path d="M 2 2 L 34 19.5 L 2 37 Z" fill="#1f1f1f" stroke="#02a783" stroke-width="4" stroke-miterlimit="10" pointer-events="all" />
        <path d="M 2 2 L 34 19.5 L 2 37 Z" fill="#1f1f1f" stroke="#02a783" stroke-width="4" stroke-miterlimit="10" pointer-events="all" />
        <path d="M 41 2 L 73 19.5 L 41 37 Z" fill="#1f1f1f" stroke="#02a783" stroke-width="4" stroke-miterlimit="10" transform="rotate(180,57,19.5)" pointer-events="all" />
      </g>
    </svg>`],

    'desalterSvg': [`<?xml version="1.0" encoding="UTF-8"?>
    <!-- Do not edit this file with editors other than diagrams.net -->
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="207px" height="94px" viewBox="-0.5 -0.5 207 94" content="&lt;mxfile host=&quot;app.diagrams.net&quot; modified=&quot;2022-12-16T10:06:35.116Z&quot; agent=&quot;5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&quot; etag=&quot;uKSZ_Oye_GGInqAzPwrg&quot; version=&quot;20.7.2&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;8cfFkvE9U_lRapClgtkz&quot; name=&quot;Page-1&quot;&gt;jZPJboMwEIafhmMkg9Msx4YsqFJPOVTKpbLwBFs1mBinkD59TTxsiiJFHDDfLMz8Mw5onDcHw0rxqTmoICK8Ceg2iKKQvBH3askNyWIdepIZyT0jAzjKP+hCkV4lhwqZR1ZrZWU5hakuCkjthDFjdD11O2vFJ6BkGTyAY8rUI/2S3ApPV11fLU9AZqL7c0jQkrPOGUElGNf1CNFdQGOjtfWnvIlBtepNddk/sfaFGSjsKwEsSQ7xaZl8XJaXdKsq+X2qZmuf5ZepKzaMxdpbp4DR14JDmyQM6KYW0sKxZGlrrd3QHRM2V2iurNE/EGulzT2akuh9uaK9pdNw7shZKjXyDPft4zgzKe6BU5lusEIwFpqnrYe9oG4VQedgzc25YABdzH0IbuGMzqkH9TDTiCATo3mucXgM1yjrcw9KuwOK3X0OQ73bRneD7v4B&lt;/diagram&gt;&lt;/mxfile&gt;">
      <defs />
      <g>
        <rect x="2" y="2" width="203" height="90" rx="45" ry="45" fill="#1f1f1f" stroke="#02a783" stroke-width="4" pointer-events="all" />
      </g>
    </svg>`]
};

